# Generated by Django 5.1.7 on 2025-04-19 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wa_id', models.CharField(db_index=True, help_text='WhatsApp User ID (Phone number with country code)', max_length=25, unique=True)),
                ('name', models.CharField(blank=True, help_text='Manually assigned or known name for the contact', max_length=255, null=True)),
                ('profile_name', models.CharField(blank=True, help_text='Name provided by WhatsApp profile (can differ from real name)', max_length=255, null=True)),
                ('marketing_opt_in', models.BooleanField(db_index=True, default=False, help_text='Indicates if the user has opted-in for marketing messages (CRITICAL for compliance)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'WhatsApp Contact',
                'verbose_name_plural': 'WhatsApp Contacts',
                'ordering': ['name', 'profile_name', 'wa_id'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(db_index=True, help_text='Unique ID provided by WhatsApp for the message', max_length=100, unique=True)),
                ('direction', models.CharField(choices=[('incoming', 'Incoming'), ('outgoing', 'Outgoing')], db_index=True, max_length=10)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('audio', 'Audio'), ('video', 'Video'), ('document', 'Document'), ('sticker', 'Sticker'), ('location', 'Location'), ('contacts', 'Contacts'), ('interactive_button_reply', 'Interactive (Button Reply)'), ('interactive_list_reply', 'Interactive (List Reply)'), ('interactive_flow', 'Interactive (Flow)'), ('template', 'Template'), ('system', 'System'), ('order', 'Order'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=30)),
                ('content', models.TextField(blank=True, help_text='Text content, media caption, template name, interactive reply description etc.', null=True)),
                ('media_url', models.URLField(blank=True, help_text='URL where received media is stored or accessible', max_length=1024, null=True)),
                ('media_mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('template_name', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('template_components', models.JSONField(blank=True, help_text='JSON data for template variables/components', null=True)),
                ('interactive_data', models.JSONField(blank=True, help_text='JSON data for interactive replies (e.g., button_reply, list_reply details, flow data)', null=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed'), ('received', 'Received'), ('pending', 'Pending'), ('sending', 'Sending'), ('cancelled', 'Cancelled')], db_index=True, help_text="Delivery status (updated via webhooks for outgoing, 'received' for incoming)", max_length=10)),
                ('whatsapp_timestamp', models.DateTimeField(db_index=True, help_text='Timestamp provided by WhatsApp in the webhook payload')),
                ('error_code', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(help_text='The contact involved in this message', on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='whatsapp_app.whatsappcontact')),
            ],
            options={
                'verbose_name': 'WhatsApp Message',
                'verbose_name_plural': 'WhatsApp Messages',
                'ordering': ['-whatsapp_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledWhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('template', 'Template'), ('text', 'Text')], default='template', help_text='Type of message to send (usually Template for marketing)', max_length=30)),
                ('template_name', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('template_components', models.JSONField(blank=True, help_text='JSON data for template variables/components', null=True)),
                ('text_content', models.TextField(blank=True, help_text='Body for plain text messages (if type is Text)', null=True)),
                ('scheduled_time', models.DateTimeField(db_index=True, help_text='The specific date and time when the message should be sent')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=10)),
                ('processing_started_at', models.DateTimeField(blank=True, help_text='When the sending task started processing', null=True)),
                ('processed_at', models.DateTimeField(blank=True, help_text='When the sending attempt finished', null=True)),
                ('celery_task_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('error_message', models.TextField(blank=True, help_text="Reason for failure if status is 'failed'", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_messages', to='whatsapp_app.whatsappcontact')),
                ('sent_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_origin', to='whatsapp_app.whatsappmessage')),
            ],
            options={
                'verbose_name': 'Scheduled WhatsApp Message',
                'verbose_name_plural': 'Scheduled WhatsApp Messages',
                'ordering': ['-scheduled_time'],
            },
        ),
    ]
