# Generated by Django 5.1.7 on 2025-04-08 05:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facebook_orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('billing_email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('billing_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('billing_first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_company', models.CharField(blank=True, max_length=200, null=True)),
                ('billing_address', models.CharField(blank=True, max_length=255, null=True)),
                ('billing_city', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_state', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_postcode', models.CharField(blank=True, max_length=20, null=True)),
                ('billing_country', models.CharField(blank=True, max_length=50, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('currency', models.CharField(blank=True, default='INR', max_length=10, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('customer_note', models.TextField(blank=True, null=True)),
                ('mode_of_payment', models.CharField(blank=True, max_length=50, null=True)),
                ('alternet_number', models.CharField(blank=True, max_length=50, null=True)),
                ('received_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('shipment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('credit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('plateform', models.CharField(blank=True, default='Facebook', max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('on-hold', 'On Hold')], db_index=True, default='pending', max_length=50)),
                ('tracking_info', models.TextField(blank=True, help_text='Enter tracking numbers, links, or carrier info here.')),
                ('internal_notes', models.TextField(blank=True, help_text='Internal staff notes about this order.')),
            ],
            options={
                'verbose_name': 'Facebook Order',
                'verbose_name_plural': 'Facebook Orders',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plant_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='facebook_app.facebook_orders')),
            ],
            options={
                'verbose_name': 'Order Product',
                'verbose_name_plural': 'Order Products',
            },
        ),
    ]
