# Generated by Django 5.1.7 on 2025-04-08 06:36

import facebook_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebook_orders',
            name='products_json',
            field=models.JSONField(blank=True, default=facebook_app.models.default_empty_list, help_text='Store product line items as a JSON list, e.g., [{"name": "Plant A", "qty": 2, "price": "150.00"}, ...]'),
        ),
        migrations.AlterField(
            model_name='facebook_orders',
            name='billing_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='OrderProduct',
        ),
    ]
