# Generated by Django 5.1.7 on 2025-04-16 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_app', '0002_facebook_orders_products_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebook_orders',
            name='shipment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('shipped', 'Shipped'), ('on-hold', 'On Hold')], db_index=True, default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='facebook_orders',
            name='billing_country',
            field=models.CharField(blank=True, default='INDIA', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='facebook_orders',
            name='order_id',
            field=models.CharField(db_index=True, help_text="Only Add Number Value Don't use any letter.", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='facebook_orders',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('on-hold', 'On Hold')], db_index=True, default='processing', max_length=50),
        ),
    ]
