# Generated by Django 5.2 on 2025-05-14 05:47

import facebook_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_app', '0003_facebook_orders_shipment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebook_orders',
            name='clone_orders',
            field=models.JSONField(blank=True, default=facebook_app.models.default_empty_list, help_text='Store clone orders as a JSON list, e.g., [{"order_id": "XXX", "platform": "facebook"}, ...]'),
        ),
    ]
