# Generated by Django 5.2 on 2025-05-28 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_app', '0004_facebook_orders_clone_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facebook_orders',
            old_name='billing_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='facebook_orders',
            old_name='billing_city',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='facebook_orders',
            old_name='billing_company',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='facebook_orders',
            old_name='billing_country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='facebook_orders',
            old_name='billing_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='facebook_orders',
            old_name='billing_first_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='facebook_orders',
            old_name='billing_last_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='facebook_orders',
            old_name='billing_phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='facebook_orders',
            old_name='billing_postcode',
            new_name='postcode',
        ),
        migrations.RenameField(
            model_name='facebook_orders',
            old_name='billing_state',
            new_name='state',
        ),
        migrations.AlterField(
            model_name='facebook_orders',
            name='plateform',
            field=models.CharField(blank=True, default='Manual', max_length=100, null=True),
        ),
    ]
