# Generated by Django 5.2 on 2025-05-28 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_app', '0005_rename_billing_address_facebook_orders_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facebook_orders',
            old_name='credit_amount',
            new_name='pending_amount',
        ),
    ]
