# Generated by Django 5.2 on 2025-05-31 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_app', '0006_rename_credit_amount_facebook_orders_pending_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facebook_orders',
            name='internal_notes',
        ),
        migrations.AddField(
            model_name='facebook_orders',
            name='unselected_items_for_clone',
            field=models.JSONField(blank=True, default=list, help_text='List of items unselected during a shipment process, intended for a future clone action.', null=True),
        ),
        migrations.AlterField(
            model_name='facebook_orders',
            name='order_id',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
