# Generated by Django 5.1.7 on 2025-04-02 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WooCommerceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('woo_id', models.PositiveIntegerField(db_index=True, help_text='WooCommerce Order ID', unique=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('customer_note', models.TextField(blank=True, null=True)),
                ('billing_first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_created_woo', models.DateTimeField(blank=True, help_text='Timestamp from WooCommerce', null=True)),
                ('date_modified_woo', models.DateTimeField(blank=True, help_text='Timestamp from WooCommerce', null=True)),
                ('django_date_created', models.DateTimeField(auto_now_add=True)),
                ('django_date_modified', models.DateTimeField(auto_now=True)),
                ('raw_data', models.JSONField(blank=True, help_text='Full webhook payload or API response', null=True)),
            ],
            options={
                'verbose_name': 'WooCommerce Order',
                'verbose_name_plural': 'WooCommerce Orders',
                'ordering': ['-date_created_woo'],
            },
        ),
    ]
