# Generated by Django 5.1.7 on 2025-04-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woocommerce_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='woocommerceorder',
            name='billing_address_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='woocommerceorder',
            name='billing_address_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='woocommerceorder',
            name='billing_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='woocommerceorder',
            name='billing_company',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='woocommerceorder',
            name='billing_country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='woocommerceorder',
            name='billing_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='woocommerceorder',
            name='billing_postcode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='woocommerceorder',
            name='billing_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='woocommerceorder',
            name='date_completed_woo',
            field=models.DateTimeField(blank=True, help_text='Timestamp from WooCommerce (UTC)', null=True),
        ),
        migrations.AddField(
            model_name='woocommerceorder',
            name='date_paid_woo',
            field=models.DateTimeField(blank=True, help_text='Timestamp from WooCommerce (UTC)', null=True),
        ),
        migrations.AddField(
            model_name='woocommerceorder',
            name='line_items_json',
            field=models.JSONField(blank=True, help_text='Raw JSON data for line items', null=True),
        ),
        migrations.AddField(
            model_name='woocommerceorder',
            name='number',
            field=models.CharField(blank=True, db_index=True, help_text='WooCommerce order number (might be different from ID)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='woocommerceorder',
            name='shipping_lines_json',
            field=models.JSONField(blank=True, help_text='Raw JSON data for shipping lines', null=True),
        ),
        migrations.AlterField(
            model_name='woocommerceorder',
            name='billing_email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='woocommerceorder',
            name='date_created_woo',
            field=models.DateTimeField(blank=True, help_text='Timestamp from WooCommerce (UTC)', null=True),
        ),
        migrations.AlterField(
            model_name='woocommerceorder',
            name='date_modified_woo',
            field=models.DateTimeField(blank=True, help_text='Timestamp from WooCommerce (UTC)', null=True),
        ),
        migrations.AlterField(
            model_name='woocommerceorder',
            name='status',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
