# Generated by Django 5.1.7 on 2025-04-05 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woocommerce_app', '0002_woocommerceorder_billing_address_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='woocommerceorder',
            name='currency',
            field=models.CharField(blank=True, default='₹', max_length=10, null=True),
        ),
    ]
