# Generated by Django 5.1.7 on 2025-04-16 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woocommerce_app', '0003_alter_woocommerceorder_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='woocommerceorder',
            name='shipment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('shipped', 'Shipped'), ('on-hold', 'On Hold')], db_index=True, default='pending', max_length=50),
        ),
    ]
