# Generated by Django 5.2 on 2025-05-27 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woocommerce_app', '0005_woocommerceproduct_woocommerceorder_clone_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='woocommerceorder',
            name='unselected_items_for_clone',
            field=models.JSONField(blank=True, default=list, help_text='List of items unselected during a shipment process, intended for a future clone action.', null=True),
        ),
    ]
