# Generated by Django 5.1.7 on 2025-04-04 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopifyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_id', models.BigIntegerField(db_index=True, help_text='Shopify Order ID', unique=True)),
                ('name', models.CharField(blank=True, db_index=True, help_text='Shopify order name (e.g., #1001)', max_length=100, null=True)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('fulfillment_status', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('financial_status', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('billing_address_json', models.JSONField(blank=True, null=True)),
                ('shipping_address_json', models.JSONField(blank=True, null=True)),
                ('created_at_shopify', models.DateTimeField(blank=True, null=True)),
                ('updated_at_shopify', models.DateTimeField(blank=True, null=True)),
                ('processed_at_shopify', models.DateTimeField(blank=True, null=True)),
                ('closed_at_shopify', models.DateTimeField(blank=True, null=True)),
                ('line_items_json', models.JSONField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('django_date_created', models.DateTimeField(auto_now_add=True)),
                ('django_date_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shopify Order',
                'verbose_name_plural': 'Shopify Orders',
                'ordering': ['-created_at_shopify'],
            },
        ),
    ]
