# Generated by Django 5.1.7 on 2025-04-05 09:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopifyorder',
            old_name='closed_at_shopify',
            new_name='losed_at_shopify',
        ),
        migrations.RemoveField(
            model_name='shopifyorder',
            name='processed_at_shopify',
        ),
        migrations.AddField(
            model_name='shopifyorder',
            name='internal_notes',
            field=models.TextField(blank=True, help_text='Internal administrative notes about this order (not from Shopify)'),
        ),
        migrations.AddField(
            model_name='shopifyorder',
            name='tracking_details_json',
            field=models.JSONField(blank=True, help_text='Store tracking numbers, URLs, carrier info, or structured fulfillment data as JSON', null=True),
        ),
        migrations.AlterField(
            model_name='shopifyorder',
            name='django_date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='shopifyorder',
            name='raw_data',
            field=models.JSONField(blank=True, help_text='Raw JSON data from API or webhook', null=True),
        ),
    ]
