# Generated by Django 5.1.7 on 2025-04-16 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_app', '0002_rename_closed_at_shopify_shopifyorder_losed_at_shopify_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifyorder',
            name='shipment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('shipped', 'Shipped'), ('on-hold', 'On Hold')], db_index=True, default='pending', max_length=50),
        ),
    ]
