# Generated by Django 5.1.7 on 2025-05-01 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_app', '0003_shopifyorder_shipment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopifyorder',
            old_name='losed_at_shopify',
            new_name='closed_at_shopify',
        ),
    ]
