# Generated by Django 5.2 on 2025-05-14 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_app', '0004_rename_losed_at_shopify_shopifyorder_closed_at_shopify'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifyorder',
            name='clone_orders',
            field=models.JSONField(blank=True, default=list, help_text="Store clone orders as a JSON list, e.g., [{'order_id': 'XXX', 'platform': 'Shopify'}, ...]"),
        ),
    ]
