# Generated by Django 5.2 on 2025-05-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_app', '0005_shopifyorder_clone_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopifyorder',
            name='fulfillment_status',
            field=models.CharField(blank=True, db_index=True, default='unfulfilled', max_length=50, null=True),
        ),
    ]
