# Generated by Django 5.2 on 2025-05-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_app', '0006_alter_shopifyorder_fulfillment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopifyorder',
            name='fulfillment_status',
            field=models.CharField(db_index=True, default='unfulfilled', max_length=50, null=True),
        ),
    ]
