# Generated by Django 5.2 on 2025-05-31 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_app', '0007_alter_shopifyorder_fulfillment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifyorder',
            name='unselected_items_for_clone',
            field=models.JSONField(blank=True, default=list, help_text='List of items unselected during a shipment process, intended for a future clone action.', null=True),
        ),
    ]
