# Generated by Django 5.2 on 2025-06-18 00:00
from django.db import migrations, models
import django.db.models.deletion
from django.contrib.auth import get_user_model


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(get_user_model()),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('value', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=get_user_model())),
            ],
            options={
                'verbose_name': 'User Setting',
                'verbose_name_plural': 'User Settings',
                'unique_together': {('user', 'key')},
            },
        ),
    ]
